#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.6ubuntu2
if [ -x "/etc/init.d/udooneo-m4uploader" ]; then
	invoke-rc.d udooneo-m4uploader stop || exit 1
fi
# End automatically added section
# Automatically added by dh_systemd_start/11.1.6ubuntu2
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'udooneo-m4uploader.service' >/dev/null || true
fi
# End automatically added section
