#!/bin/sh
set -e
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop udoo-gpio-export.service >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/udoo-gpio-export" ] || [ -e "/etc/init/udoo-gpio-export.conf" ]; then
	invoke-rc.d udoo-gpio-export stop || exit $?
fi
# End automatically added section
