#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.6ubuntu2
if [ -x "/etc/init.d/udooneo-bluetooth" ]; then
	invoke-rc.d udooneo-bluetooth stop || exit 1
fi
# End automatically added section
# Automatically added by dh_systemd_start/11.1.6ubuntu2
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'udooneo-bluetooth.service' >/dev/null || true
fi
# End automatically added section
